development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:be44e75d537030b0bb4aa613ef089a9c@jack.redistogo.com:11879/
  channel_prefix: air-one_production
